### ISSUE TITLE
Changes saved to both reversed cards

### ISSUE THREAD

**Issue by one2three4f** [BlueGreenMagick/Edit-Field-During-Review-Cloze#111]
**Describe the bug**
When I update a keyword card while reviewing, both of the corresponding reverse cards are updated.

**To Reproduce**
1. Create a reversed card
2. Edit the reversed card during a review session
3. Open the browse menu while reviewing to check corresponding cards
4. Both reversed cards reflect changes

**Screenshots**
If applicable, please add screenshots to help explain your problem.

![image](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/143331948/0289a908-53fa-46b4-845c-5439ec3dcdc6)
![image](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/assets/143331948/92a89185-7f2e-4430-bb42-386bc04c50ec)

**Comment by BlueGreenMagick** [comment]
That's because it's the same note. The content belongs to a note, and the note is just a 'view' of the note content. It's not possible to edit the content of only one of the cards of the same note in Anki.

If you want to have the two cards have different content, you need to create two different notes.
