### ISSUE TITLE
Not functional since 11/14 update

### ISSUE THREAD

**Issue by nathandavies11** [BlueGreenMagick/Edit-Field-During-Review-Cloze#126]
The below checklist isn't manditory, but suggested before creating an issue.
- [x] I've updated this add-on to the latest version
- [x] I've tried disabling all other add-ons except this one.

**Describe the bug**
What is the bug, and what behaviour did you expect instead?

**To Reproduce**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Debug Info**
In the toolbar, go to `Help > About...`. In the About window, click the `Copy Debug Info` button at the bottom beside an 'OK' button. Please paste the contents below.

**Comment by nathandavies11** [comment]
2.1.65 (aa9a734f)⁩

**Comment by BlueGreenMagick** [comment]
I'm unable to reproduce the problem. I've tested on v2.1.50, 64, 24.04.1 and 24.06.3 and it all works fine on my machine.

Is there some kind of an error message? 

If not, can you try debugging with the [AnkiWebview Inspector](https://ankiweb.net/shared/info/31746032) add-on? Try to edit the card in the reviewer, then open the inspector and see if there are any errors in the 'console' tab.

**Comment by lockey530** [comment]
hey tried to download the older version of the add on but it is not working also. any work around really love this add on.

**Comment by BlueGreenMagick** [comment]
@lockey530 Can you help me figure out what the problem is? 

What Anki version are you using? Also, below information would be immensely useful.

> I'm unable to reproduce the problem. I've tested on v2.1.50, 64, 24.04.1 and 24.06.3 and it all works fine on my machine.
> 
> Is there some kind of an error message?
> 
> If not, can you try debugging with the [AnkiWebview Inspector](https://ankiweb.net/shared/info/31746032) add-on? Try to edit the card in the reviewer, then open the inspector and see if there are any errors in the 'console' tab.

**Comment by lockey530** [comment]
I'm on version version ⁨24.06.3. not getting any error message!

**Comment by BlueGreenMagick** [comment]
1. Can you copy paste the Anki debug info? You can find the button at the bottom of 'About Anki' window.
2. Can you check that the fields were configured to be editable? In the add-on config, go to the 'Fields' tab, and check that fields for note types are checked.

**Comment by lockey530** [comment]
![Screenshot 2024-11-16 at 2 29 30 PM](https://github.com/user-attachments/assets/1e293085-6714-47ef-92a9-e9daadd2b72c)
oh hey is this error related?

**Comment by lockey530** [comment]
sorry the spam!

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-13.6.7-x86_64-i386-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T22:24, 'None', mod]
Add Table ['1237621971', 2023-06-18T19:37, 'None', mod]
Advanced Browser ['874215009', 2024-10-27T22:20, 'None', mod]
Always On Top - permanently keep Anki as top Fixed by Shige ['1045980020', 2024-05-02T09:22, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-10-21T22:29, 'None', mod]
Anki Killstreaks - Reward Medals for Correct Answers Fixed by Shige ['1562475180', 2024-09-20T02:43, 'None', mod]
Anki Simulator ['817108664', 2023-11-07T01:26, 'None', '']
Anki Terminator - ChatGPT Sidebar for Review GoogleGemini Created by Shige ['1428126516', 2024-09-04T22:54, 'None', mod]
Anki Zoom ['538879081', 2020-04-04T08:20, 'v1.1.3', mod]
AnkiHub ['1322529746', 2024-11-13T01:38, 'None', mod]
AnkiOCR - Generate OCR text from images Fixed for Anki 23  by Shige ['546383173', 2024-02-22T06:06, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-28T03:26, 'None', '']
Auto Sync QT5 ['394763593', 2024-07-23T12:14, 'None', '']
Automatically rebuild filtered deck ['1997713323', 2021-07-18T23:18, 'None', '']
Batch Editing ['291119185', 2023-10-26T08:38, 'None', '']
BetterSearch ['1052724801', 2024-03-07T00:25, 'None', '']
Bionic Reading ['649714433', 2023-10-27T05:24, 'None', mod]
Calculate New Cards To Do ['2014569756', 2022-05-19T13:38, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-31T06:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T16:27, 'None', '']
Congrats Confetti ['206062158', 2023-01-17T12:02, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T19:50, 'None', '']
Customize Keyboard Shortcuts ['24411424', 2023-11-01T17:17, 'None', mod]
Edit Field During Review (Cloze) ['edit-field-during-review-cloze', 0, '6.19', mod]
Extended Tag AddEdit Dialog ['1135507717', 2023-11-12T00:58, 'None', mod]
External Note Editor for the Browser ['browser_external_note_editor', 2020-03-11T01:42, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-15T11:46, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T19:47, 'None', '']
Find cards from UWorld test ['444814983', 2024-07-19T14:19, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-22T03:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T22:13, 'None', '']
Hitmarkers ['1776869150', 2024-02-24T19:19, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Localize Media ['1293255374', 2023-10-19T11:14, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-20T06:49, 'None', '']
Motivanki ['663438166', 2022-06-23T23:38, 'None', '']
New Cards Counter ['635082046', 2022-04-21T04:37, 'None', mod]
Opening the same window multiple time ['354407385', 2023-11-05T09:59, 'None', '']
PDF Exporter ['1442112168', 2023-03-21T07:53, 'None', '']
PDF Glossary Exporter ['pdf_glossary', 2019-08-19T20:35, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2024-06-04T09:56, 'None', '']
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T14:26, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-11-11T04:00, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T20:59, 'None', '']
Rearrange home addons Created by Shige ['1797615099', 2024-08-28T02:00, 'None', mod]
Remove card history ['2089200096', 2023-10-19T11:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-04-01T04:13, 'None', '']
Search Stats Extended ['1613056169', 2024-10-24T19:02, 'None', mod]
Set Added Date ['1124670306', 2023-07-17T01:31, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', mod]
Syllabus - Anki Statistics and Export by Tag and Deck Fixed by Shige ['1403834620', 2024-05-29T19:53, 'None', '']
Tag Statistics - Fixed for Anki 23 by Shige ['1269070743', 2024-03-07T01:20, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-09-23T20:14, 'None', '']
The KING of Study Timers ['907028815', 2022-04-21T02:14, 'None', mod]
True Retention ['613684242', 2017-11-20T04:43, 'None', '']
Weekends and Holidays ['1992008104', 2022-12-20T09:24, 'None', mod]
link Cards Notes and Preview them in extra window ['1423933177', 2023-10-28T06:26, 'None', '']
pasteOCR ['1746010116', 2023-02-27T06:47, 'None', '']

===IDs of active AnkiWeb add-ons===
1045980020 1046608507 1052724801 1124670306 1135507717 1143540799 1237621971 1269070743 1293255374 1322529746 1374772155 1403834620 1423933177 1428126516 1442112168 1556734708 1562475180 1613056169 1708250053 1722658993 1739176371 1746010116 1771074083 1776869150 1797615099 1844908621 1992008104 1997713323 2014569756 206062158 2089200096 225180905 24411424 266436365 272311064 291119185 31746032 354407385 374005964 394763593 444814983 46611790 538879081 546383173 613684242 635082046 649714433 663438166 759844606 817108664 874215009 876946123 907028815 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Copy Fields ['1898445115', 2024-01-09T01:01, 'v0.4.01', '']
Anki Format Shuffler ['148580004', 2024-08-10T07:19, 'None', '']
Anki Killstreaks ['579111794', 2021-12-15T23:20, 'None', mod]
Anki Note Linker ['1077002392', 2024-10-12T20:06, 'None', mod]
Auto Sync ['501542723', 2023-11-21T00:14, 'None', '']
Beautify-Anki 20 mizmu ['1116770498', 2023-11-01T02:51, 'None', mod]
Echelon - Improved Hierarchical Tags for Anki 21 - Unsupported ['829533913', 2019-11-18T07:54, 'None', '']
Enhance main window Customized by Shige ['911023479', 2024-10-12T14:18, 'None', mod]
Freshness - Randomize CSS styles ['1369362778', 2023-04-24T04:39, 'None', '']
HUMBLE PIE distinct cards studied today statistic ['2133933791', 2020-03-25T02:05, 'None', '']
Leaderboard ['41708974', 2023-01-15T18:53, 'None', '']
Life Drain ['715575551', 2024-04-30T15:15, 'None', mod]
No Distractions Full Screen Fixed by Shige ['1370336700', 2024-08-26T13:08, 'None', mod]
No Space Dash-Prevents answer for 15 seconds-Fixed for Anki 23 by Shige ['1573867049', 2024-02-26T23:21, '20.12.25i94', '']
No longer needed LeaderBoard Patch Installer Fixed for Mac by Shige ['1464611181', 2024-06-26T19:15, 'None', mod]
Play a celebrationcompletion sound when you finish your deck ['978869609', 2024-01-12T12:43, 'None', '']
Progress Bar original ['1685464019', 2022-07-28T13:24, 'None', mod]
Skip Anki home and deck overview Customized by Shige ['295525470', 2024-09-29T05:49, 'None', mod]
Straight Reward ['957961234', 2023-11-01T22:11, 'None', '']
Study Time Stats ['1247171202', 2024-02-25T00:59, 'None', '']
Study-Review Deck ['1026503859', 2024-07-16T19:08, '0.2.1', '']
Symbols As You Type FIXED ['2088399109', 2023-12-15T02:45, 'None', '']

**Comment by BlueGreenMagick** [comment]
Thanks for the detailed report! I didn't think to check Qt5 versions. 

The fix should be uploaded tomorrow at the latest.
