### ISSUE TITLE
Compatibility with Custom Styles font color background colour classes

### ISSUE THREAD

**Issue by petercla0119** [BlueGreenMagick/Edit-Field-During-Review-Cloze#41]
Great add-on! Exactly the thing I was looking for!

One issue: it doesn't seem to work with the Custom Styles font color background colour classes add-on. Which I use to emphasize terms on my cards. My keyboard shortcuts still work in the editor window, but not during review.

Any suggestions on how to use these add-ons together?

**Comment by BlueGreenMagick** [comment]
Custom Styles font color background colour classes add-on only lets you use the shortcuts in the Editor. While this addon lets you edit while reviewing, it is still the Reviewer, not Editor. So that addon does not recognize edit during reviewing as editing.

I suspect the work needed to Add the functionality to the Reviewer would be similar creating a whole new addon. So unfortunately, I must decide that it's out of scope for this addon. You _could_ open a feature request in the other addon's github repo, but imo it's rather unlikely to be added there as well.
